backend:
  name: github
  repo: quyt0/astro-def # Path to your GitHub repository
  # optional, defaults to master
  branch: main

publish_mode: editorial_workflow

media_folder: "/assets/img"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored new for 1.4
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" 
    fields: # The fields for each document
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "pubDate", widget: "datetime"}
      - {label: "Featured Image", name: "heroImage", widget: "image", required: false} # set required to false can remove if you need 
      - {label: "Body", name: "body", widget: "markdown"}